// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-6JAAOPTnV21w1l9asMHQItPaoQNd2V8',
    appId: '1:3547833271:web:8839f4122a33a70ad1fe32',
    messagingSenderId: '3547833271',
    projectId: 'miapp5afirebase-ede9a',
    authDomain: 'miapp5afirebase-ede9a.firebaseapp.com',
    storageBucket: 'miapp5afirebase-ede9a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQRbcRndhvxxoRmsXVtm9FIA5LrYztPts',
    appId: '1:3547833271:android:52e78002c0d98d07d1fe32',
    messagingSenderId: '3547833271',
    projectId: 'miapp5afirebase-ede9a',
    storageBucket: 'miapp5afirebase-ede9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTEKAFnzsQsABX2XTJ6fJmdis87ZJpxj4',
    appId: '1:3547833271:ios:8ef79885ddc92fa5d1fe32',
    messagingSenderId: '3547833271',
    projectId: 'miapp5afirebase-ede9a',
    storageBucket: 'miapp5afirebase-ede9a.firebasestorage.app',
    iosBundleId: 'com.edgardonaldo.appfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTEKAFnzsQsABX2XTJ6fJmdis87ZJpxj4',
    appId: '1:3547833271:ios:8ef79885ddc92fa5d1fe32',
    messagingSenderId: '3547833271',
    projectId: 'miapp5afirebase-ede9a',
    storageBucket: 'miapp5afirebase-ede9a.firebasestorage.app',
    iosBundleId: 'com.edgardonaldo.appfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-6JAAOPTnV21w1l9asMHQItPaoQNd2V8',
    appId: '1:3547833271:web:236433b709b3e4ecd1fe32',
    messagingSenderId: '3547833271',
    projectId: 'miapp5afirebase-ede9a',
    authDomain: 'miapp5afirebase-ede9a.firebaseapp.com',
    storageBucket: 'miapp5afirebase-ede9a.firebasestorage.app',
  );
}
